services:

  mariadb:
    container_name: mariadb		
    env_file: .env    	
    networks:
    - inception                		
    build: 
      context: requirements/mariadb 
      dockerfile: Dockerfile			
      args:
        DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}          
    volumes:                        
    - mariadb:/var/lib/mysql
    restart: unless-stopped 

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
    - wordpress:/var/www/html/wordpress
    networks:
    - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
    - mariadb
    restart: on-failure
          
  nginx:
    container_name: nginx
    volumes:
    - wordpress:/var/www/html/wordpress
    networks:
    - inception
    depends_on: 
    - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
    - "443:443"
    restart: on-failure


  redis:
    container_name: redis
    networks:
    - inception
    depends_on: 
    - nginx
    build:
      context: requirements/bonus/redis
      dockerfile: Dockerfile
    env_file: .env
    ports:
     - '6379:6379'
    restart: on-failure

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer/.
    image: adminer
    depends_on:
      - mariadb
    ports:
      - "600:80"
    networks:
      - inception
    restart: always

  cadvisor:
    container_name: cadvisor
    build: ./requirements/bonus/cadvisor/.
    image: cadvisor
    depends_on:
      - redis
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      # - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - inception
    restart: always

  ftp:
    container_name: ftp
    env_file: .env    
    build: ./requirements/bonus/ftp/.
    image: ftp
    depends_on:
      - redis
    ports:
      - "21100-21110:21100-21110"
      - "20:20"
      - "21:21"
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception
    restart: always

volumes:
  wordpress:
    driver: local
    driver_opts: 
      type: 'none' 								
      o: 'bind'
      device: '/home/teliet/data/wordpress' 		
  mariadb:
    driver: local
    driver_opts: 
      type: 'none' 
      o: 'bind'										 
      device: '/home/teliet/data/mariadb'			

networks:
    inception:
      driver: bridge		