services:

  mariadb:
    container_name: mariadb		
    env_file: .env    	
    networks:
    - inception                		
    build: 
      context: requirements/mariadb 
      dockerfile: Dockerfile			
      args:
        DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}          
    volumes:                        
    - mariadb:/var/lib/mysql
    restart: unless-stopped       
    expose:                       
    - "3306"

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
    - wordpress:/var/www/html/wordpress
    networks:
    - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
    - mariadb
    restart: on-failure
    expose: 
    - "9000"
          
  nginx:
    container_name: nginx
    volumes:
    - wordpress:/var/www/html/wordpress
    networks:
    - inception
    depends_on: 
    - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
    - "443:443"
    restart: on-failure


  redis:
    container_name: redis
    networks:
    - inception
    depends_on: 
    - nginx
    build:
      context: requirements/bonus/redis
      dockerfile: Dockerfile
    env_file: .env
    ports:
    - "444"
    restart: on-failure

volumes:
  wordpress:
    driver: local
    driver_opts: 
      type: 'none' 								
      o: 'bind'
      device: '/home/teliet/data/wordpress' 		
  mariadb:
    driver: local
    driver_opts: 
      type: 'none' 
      o: 'bind'										 
      device: '/home/teliet/data/mariadb'			

networks:
    inception:
      driver: bridge		